version: '3.8'

services:
  db_postgres:
    build:
      context: .
      dockerfile: Dockerfile-database
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts_database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgres:5432/mydatabase
    depends_on:
      - "db_postgres"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080      

volumes:
  pgdata: