CREATE TABLE public.record (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	canceled bool NOT NULL,
	customer varchar(255) NULL,
	date_time timestamp(6) NULL,
	done bool NOT NULL,
	"location" varchar(255) NULL,
	service varchar(255) NULL,
	CONSTRAINT record_pkey PRIMARY KEY (id)
);

INSERT INTO public.record (canceled, customer, date_time, done, Location, service)
VALUES
(false, 'Ana Carla', (SELECT CURRENT_DATE), false, 'R. Cravo, 25', 'Mani e Pedi'),
(false, 'Carlos Oliveira', (SELECT CURRENT_DATE), false, 'Av. Lírios, 22', 'Corte de Cabelo'),
(false, 'Fernanda Santos', (SELECT CURRENT_DATE), false, 'Tr. Orquídeas, 33', 'Limpeza de Pele'),
(false, 'Luciana Lima', (SELECT CURRENT_DATE), false, 'R. Violetas, 40', 'Massagem Relax'),
(false, 'Ana Silva', (SELECT CURRENT_DATE), false, 'R. Rosas, 15', 'Mani e Pedi'),
(false, 'Carlos Oliveira', (SELECT CURRENT_DATE), false, 'Av. Lírios, 22', 'Corte de Cabelo'),
(false, 'Fernanda Santos', (SELECT CURRENT_DATE), false, 'Tr. Orquídeas, 33', 'Limpeza de Pele'),
(false, 'Luciana Lima', (SELECT CURRENT_DATE), false, 'R. Violetas, 40', 'Massagem Relax'),
(false, 'Ricardo Pereira', (SELECT CURRENT_DATE), false, 'Al. Jasmins, 12', 'Depilação'),
(false, 'Cristina Oliveira', (SELECT CURRENT_DATE), false, 'R. Margaridas, 28', 'Des. Sobrancelhas'),
(false, 'Paulo Santos', (SELECT CURRENT_DATE), false, 'Av. Hortênsias, 5', 'Trat. Facial'),
(false, 'Mariana Costa', (SELECT CURRENT_DATE), false, 'R. Begônias, 18', 'Pedicure'),
(false, 'Gabriel Silva', (SELECT CURRENT_DATE), false, 'Tr. Gérberas, 9', 'Corte Masculino'),
(false, 'Isabela Santos', (SELECT CURRENT_DATE), false, 'Al. Cravos, 25', 'Coloração Cabelo'),
(false, 'Eduardo Lima', (SELECT CURRENT_DATE), false, 'R. Orquídeas, 14', 'Spa Facial'),
(false, 'Aline Oliveira', (SELECT CURRENT_DATE), false, 'Av. Jasmins, 20', 'Manicure'),
(false, 'Rafael Silva', (SELECT CURRENT_DATE), false, 'Tr. Begônias, 7', 'Penteado'),
(false, 'Camila Santos', (SELECT CURRENT_DATE), false, 'Al. Violetas, 30', 'Maquiagem'),
(false, 'Rodrigo Lima', (SELECT CURRENT_DATE), false, 'R. Cravos, 42', 'Reflexologia'),
(false, 'Juliana Oliveira', (SELECT CURRENT_DATE), false, 'Av. Lírios, 8', 'Banho de Lua'),
(false, 'Daniel Santos', (SELECT CURRENT_DATE), false, 'Tr. Orquídeas, 25', 'Corte Feminino'),
(false, 'Laura Silva', (SELECT CURRENT_DATE), false, 'R. Jasmins, 16', 'Hidratação Capilar'),
(false, 'Felipe Oliveira', (SELECT CURRENT_DATE), false, 'Al. Begônias, 11', 'Pedicure'),
(false, 'Mariana Santos', (SELECT CURRENT_DATE),false, 'Av. Violetas, 33', 'Coloração de Unhas'),
(false, 'Lucas Lima', (SELECT CURRENT_DATE), false, 'R. Orquídeas, 19', 'Massagem'),
(false, 'Beatriz Oliveira', (SELECT CURRENT_DATE), false, 'Tr. Jasmins, 7', 'Design de Barba'),
(false, 'Vinícius Silva', (SELECT CURRENT_DATE), false, 'Al. Cravos, 22', 'Banho de Espuma'),
(false, 'Carolina Santos', (SELECT CURRENT_DATE), false, 'Av. Lírios, 14', 'Maquiagem Social'),
(false, 'Gustavo Lima', (SELECT CURRENT_DATE), false, 'R. Orquídeas, 30', 'Pedicure Masculino'),
(false, 'Fernanda Oliveira', (SELECT CURRENT_DATE), false, 'Tr. Violetas, 18', 'Spa dos Pés');

